
#----------------------------
# Global kubernetes variables
#----------------------------
kube_package_version: 1.9.6
kube_release_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kube_package_version }}/bin/linux/amd64"
kube_kubectl_package_url: "{{ kube_release_url }}/kubectl"
kube_binary_path: /usr/local/bin
kube_conf_path: /etc/kubernetes
kube_data_dir: /var/lib/kubernetes
kube_api_server: https://apiserver.k8s.lan
kube_ressources_path: "{{ kube_data_dir }}/ressources"
kube_certs_path: "{{ kube_data_dir }}/certs"
kube_kubeconfig_path: "{{ kube_data_dir }}"
kube_tls_cert: "{{ kube_certs_path }}/kubernetes.pem"
kube_tls_key: "{{ kube_certs_path }}/kubernetes-key.pem"
kube_tls_ca: "{{ kube_certs_path }}/ca.pem"
kube_use_local_binaries: no
kube_local_binaries_path: /tmp/k8s-binaries

#-----------------------------------
# Common kubernetes master variables
#-----------------------------------
kube_master_package_version: "{{ kube_package_version }}"
kube_master_release_url: "{{ kube_release_url }}"
kube_master_kubectl_package_url: "{{ kube_release_url }}/kubectl"
kube_master_binary_path: "{{ kube_binary_path }}"
kube_master_conf_path: "{{kube_conf_path  }}"
kube_master_data_dir: "{{ kube_data_dir }}"
kube_master_api_server: "{{ kube_api_server }}"
kube_master_ressources_path: "{{ kube_ressources_path }}"
kube_master_certs_path: "{{ kube_certs_path }}"
kube_master_kubeconfig_path: "{{ kube_kubeconfig_path }}"
kube_master_tls_cert: "{{ kube_tls_cert }}"
kube_master_tls_key: "{{ kube_tls_key }}"
kube_master_tls_ca: "{{ kube_tls_ca }}"

#-----------------------------------
# Common kubernetes worker variables
#-----------------------------------
kube_worker_package_version: "{{ kube_package_version }}"
kube_worker_release_url: "{{ kube_release_url }}"
kube_worker_kubectl_package_url: "{{ kube_worker_release_url }}/kubectl"
kube_worker_binary_path: "{{ kube_binary_path }}"
kube_worker_conf_path: "{{kube_conf_path  }}"
kube_worker_data_dir: "{{ kube_data_dir }}"
kube_worker_api_server: "{{ kube_api_server }}"
kube_worker_certs_path: "{{ kube_certs_path }}"
kube_worker_kubeconfig_path: "{{ kube_kubeconfig_path }}"
kube_worker_tls_cert: "{{ kube_tls_cert }}"
kube_worker_tls_key: "{{ kube_tls_key }}"
kube_worker_tls_ca: "{{ kube_tls_ca }}"

#----------------------------------
# Global worker services parameters
#----------------------------------
kube_worker_allow_privileged: yes
kube_worker_log_level: 2

#---------------------------------------------------
# Kubelet variables for worker cluster configuration
#---------------------------------------------------
kubeconfig_name: kubernetes
kubeconfig_api_server: "{{ kube_worker_api_server }}"
kubeconfig_user_token: hbgith7aWi1aegheifeRhdaiLahVie3z