---

- name: docker / install - create mandatory directory
  file:
    state: directory
    path: "{{ kubelet.conf_path }}"
  become: yes

- name: docker / install - test docker binaries presence
  stat:
    path: "{{ docker.binary_path }}/docker"
  register: docker_binary

- name: docker / install - install docker binaries
  block:
  - name: docker / install - download and extract docker tarball
    unarchive:
      src: "{{ docker.release_url }}/docker-{{ docker.version }}.tgz"
      dest: "{{ docker.src_temp_path }}"
      remote_src: yes

  - name: docker / install - move docker binaries then clean /tmp
    shell: |
      mv {{ docker.src_temp_path }}/docker/* /usr/local/bin
      chmod +x /usr/local/bin/docker*
      rm -rf /tmp/docker*
    become: yes
  when: not docker_binary.stat.exists


- name: docker / certificates - manage certificates for docker
  block:
  - name: docker / certificates - create fqdn repository
    file:
      state: directory
      path: "/etc/docker/certs.d/{{ docker.cert_fqdn }}"
      recurse: yes
    notify:
      - restart docker

  - name: docker / certificates - copy certificates to docker certs.d
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: yes
    with_items:
      - src: "{{ kube_worker_tls_cert_file }}"
        dest: "/etc/docker/certs.d/{{ docker.cert_fqdn }}/client.cert"
      - src: "{{ kube_worker_tls_private_key_file }}"
        dest: "/etc/docker/certs.d/{{ docker.cert_fqdn }}/client.key"
      - src: "{{ kube_worker_tls_ca_file }}"
        dest: "/etc/docker/certs.d/{{ docker.cert_fqdn }}/ca.crt"
    notify:
      - restart docker
  become: yes
  when: docker.cert_enable

- name: docker / configure - define systemd environment file for docker
  template:
    src: "templates/configuration/{{ file }}.j2"
    dest: "/etc/kubernetes/{{ file }}"
  notify:
    - restart docker
  with_items:
    - worker
    - docker
  loop_control:
    loop_var: file
  become: yes

- name: docker / configure - define systemd service for docker
  template:
    src: templates/systemd/docker.service.j2
    dest: /etc/systemd/system/docker.service
  notify:
    - restart docker
  become: yes

- name: docker / configure - enable docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: docker - restart docker on condition
  command: /bin/true
  notify: restart docker
  when: docker.service_force_restart