---

# - name: kubelet -  set servers fact
#   set_fact:
#     kubelet_api_servers: |
#       {% for server in kubelet.api_servers -%}
#       {{ kubelet.protocol }}://{{ hostvars[server].ansible_default_ipv4.address }}:{{ kubelet.api_port }},
#       {%- endfor %}

- name: kubelet / install - create mandatory directories
  file:
    state: directory
    path: "{{ directory }}"
  with_items:
    - "{{ kubelet.binary_path }}"
    - "{{ kubelet.kubeconfig_path }}"
    - "{{ kubelet.conf_path }}"
  loop_control:
    loop_var: directory
  become: yes

- name: kubelet / install - download kubelet binary
  get_url:
    url: "{{ kubelet.package_url }}"
    dest: "{{ kubelet.binary_path }}/kubelet"
    mode: 0755
  become: yes

- name: kubelet / configure - copy kubeconfig configuration
  copy:
    content: "{{ kubelet.configuration | to_nice_yaml }}"
    dest: "{{ kubelet.kubeconfig_path }}/kubeconfig"
  become: yes

- name: kubelet / configure - define systemd environment file for kubelet
  template:
    src: "templates/configuration/{{ file }}.j2"
    dest: "/etc/kubernetes/{{ file }}"
  notify:
    - restart kubelet
  with_items:
    - worker
    - kubelet
  loop_control:
    loop_var: file
  become: yes

- name: kubelet / configure - define systemd service for kubelet
  template:
    src: templates/systemd/kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
    - restart kubelet
  become: yes

- name: kubelet - enable kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes
  become: yes

- name: kubelet / log - display cmd launched through systemd in file
  shell: pgrep -a kubelet >/tmp/kubelet.cmd
  become: yes