---

- name: main - install docker
  include: docker.yml
  tags:
    - docker

- name: main - install cni plugin
  include: cni.yml
  tags:
    - cni

- name: main - install kubelet server
  include: kubelet.yml
  tags:
    - kubelet