---

- name: ressources - deploy system components to kubernetes cluster
  block:
  - name: ressources - deploy network to kubernetes cluster
    shell: /usr/local/bin/kubectl create -f /var/lib/kubernetes/ressources/kube-system/flannel.yml
  - name: ressources - deploy dns to kubernetes cluster
    shell: /usr/local/bin/kubectl create -f /var/lib/kubernetes/ressources/kube-system/dns.yml
  - name: ressources - deploy loadbalancer traefik to kubernetes cluster
    shell: /usr/local/bin/kubectl create -f /var/lib/kubernetes/ressources/kube-system/traefik.yml
  - name: ressources - deploy dashboard to kubernetes cluster
    shell: /usr/local/bin/kubectl create -f /var/lib/kubernetes/ressources/kube-system/dashboard.yml
  no_log: yes
  ignore_errors: yes
  delegate_to: "{{ groups['masters'] | first }}"
  when: create_ressources
