
- name: fluentd / configure - define systemd service for fluentd
  template:
    src: templates/fluentd.service.j2
    dest: /etc/systemd/system/fluentd.service
  notify:
    - restart fluentd
  become: yes

- name: fluentd / configure - add configuration files
  copy:
    src: "files/{{ file }}.conf"
    dest: "/etc/fluent/{{ file }}.conf"
    mode: 0640
  with_items:
    - fluent
    - kubernetes
    - systemd
  loop_control:
    loop_var: file
  become: yes

# - name: fluentd / configure - enable fluentd service
#   service:
#     name: fluentd
#     state: started
#     enabled: yes
#   become: yes
#
# - name: fluentd / configure - restart fluentd on condition
#   command: /bin/true
#   become: yes
#   notify:
#     - restart fluentd
#   when:
#     - fluentd_service_force_restart