---

- name: install - create mandatory directories
  file:
    state: directory
    path: "{{ directory }}"
  with_items:
    - "{{ kube_master_binary_path }}"
    - "{{ kube_master_kubeconfig_path }}"
  loop_control:
    loop_var: directory
  become: yes

- name: install - download kubectl binary
  get_url:
    url: "{{ kubectl_package_url }}"
    dest: "{{ kube_master_binary_path }}/kubectl"
    mode: 0755
  become: yes