---

- name: main - install kube-api-server
  include: kube-api-server.yml
  tags:
    - kube-apiserver

- name: main - install kube-controller-manager
  include: kube-controller-manager.yml
  tags:
    - kube-controller-manager

- name: main - install kube-scheduler
  include: kube-scheduler.yml
  tags:
    - kube-scheduler

- name: main - install token, policies and kubectl
  include: common.yml
  tags:
    - common