---

- name: main - install kube-api-server
  include: kube-api-server.yml
  tags:
    - api-server

- name: main - install kube-controller-manager
  include: kube-controller-manager.yml
  tags:
    - controller-manager

- name: main - install kube-scheduler
  include: kube-scheduler.yml
  tags:
    - scheduler