---


- name: main - include common variables from default main file
  include_vars:
    file: ../defaults/main.yml
  tags: always

- name: main - include default variables
  include_vars:
    file: "../defaults/{{ item }}.yml"
    name: "{{ item | regex_replace('-', '_') }}_default"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  tags: always

- name: main - merge default variables with overriden ones
  set_fact:
    "{{ item.variable }}": "{{ item.default | combine(item.data) }}"
  with_items:
    - variable: kube_apiserver
      data: "{{ kube_apiserver | default({}) }}"
      default: "{{ kube_apiserver_default | default({})}}"
    - variable: kube_controller_manager
      data: "{{ kube_controller_manager | default({})}}"
      default: "{{ kube_controller_manager_default | default({})}}"
    - variable: kube_scheduler
      data: "{{ kube_scheduler | default({})}}"
      default: "{{ kube_scheduler_default | default({})}}"
  no_log: yes
  tags: always

- name: main - create mandatory directories
  file:
    state: directory
    path: "{{ directory }}"
  with_items:
    - "{{ kube_master_binary_path }}"
    - "{{ kube_master_kubeconfig_path }}"
  loop_control:
    loop_var: directory
  become: yes

- name: main - download kubectl binary
  get_url:
    url: "{{ kube_master_kubectl_package_url }}"
    dest: "{{ kube_master_binary_path }}/kubectl"
    mode: 0755
  become: yes

- name: main - install kube-api-server
  include: kube-api-server.yml
  tags:
    - kube-apiserver

- name: main - install kube-controller-manager
  include: kube-controller-manager.yml
  tags:
    - kube-controller-manager

- name: main - install kube-scheduler
  include: kube-scheduler.yml
  tags:
    - kube-scheduler