---

# cloudflare ssl
cfssl_certs_path: /etc/ssl/cfssl/certs
cfssl_generation_local_certs_path: /tmp/cfssl_certs
cfssl_binary_url: "https://pkg.cfssl.org/R1.2/cfssl_linux-amd64"
cfssl_json_binary_url: "https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64"

cfssl_force: no
cfssl_upload_only: no
cfssl_signing_default_expiry: 8760h
cfssl_signing_profiles:
  kubernetes:
    usages:
      - signing
      - key encipherment
      - server auth
      - client auth
    expiry: 8760h

cfssl_ca_csr:
  cn: Kubernetes
  key:
    algo: rsa
    size: 2048
  names:
    - C: FR
      L: Paris
      O: Kubernetes
      OU: Cluster
      ST: Ile-de -France

cfssl_clients_csr:
  cn: Kubernetes
  hosts:
    - 127.0.0.1
    - 10.32.0.1
  key:
    algo: rsa
    size: 2048
  names:
    - C: FR
      L: Paris
      O: Kubernetes
      OU: Cluster
      ST: Ile-de-France