Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')

IMAGE = 'debian/stretch64'
NODES = [
  'test-vagrant-base-box'
]

CONFIGURATION_VERSION = 2
Vagrant.configure(CONFIGURATION_VERSION) do |config|
  config.vm.box = IMAGE

  NODES.each do |node_name|
    config.vm.define node_name do |node|
      node.vm.hostname = node_name
      node.vm.provider :lxc do |lxc|
        lxc.container_name  = :machine
        lxc.customize 'network.link', 'lxc-bridge'
      end

      config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{ENV['ANSIBLE_PERSONAL_PUBKEYFILE']}").first.strip
        s.inline = <<-SHELL
          adduser #{ENV['ANSIBLE_PERSONAL_USER']} --disabled-password --gecos ""
          echo #{ENV['ANSIBLE_PERSONAL_USER']}:vagrant | chpasswd
          mkdir -p /home/#{ENV['ANSIBLE_PERSONAL_USER']}/.ssh
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /home/#{ENV['ANSIBLE_PERSONAL_USER']}/.ssh/authorized_keys
          echo "#{ENV['ANSIBLE_PERSONAL_USER']} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/#{ENV['ANSIBLE_PERSONAL_USER']}
        SHELL
      end
    end
  end
end