---

- name: install - download cfssl binaries
  get_url:
    url: "{{ binary.url }}"
    dest: "{{ binary.file }}"
    mode: 0755
  with_items:
    - url: "{{ cfssl_binary_url }}"
      file: /usr/local/bin/cfssl
    - url: "{{ cfssl_json_binary_url }}"
      file: /usr/local/bin/cfssljson
  loop_control:
    loop_var: binary
  become: yes