---

- name: main - define csr hosts to match
  set_fact:
    csr_defined: "{{ cfssl_clients_csr.hosts }}"
    csr_fqdn: "{{ ansible_play_hosts | map('extract', hostvars, 'ansible_fqdn') | list }}"
    csr_ips: "{{ ansible_play_hosts | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"

- name: main - check existence of cert directory
  stat:
    path: "{{ cfssl_certs_path }}"
  register: cert_directory

- name: main - install cloudflare and generate certificates locally
  include: install.yml
  tags:
    - install
  when:
    - cfssl_force or not cert_directory.stat.exists
    - not cfssl_upload_only

- name: main - upload cloudflare certificates
  include: upload.yml
  tags:
    - upload
  when: cfssl_force or not cert_directory.stat.exists
