#-----------------------------------
# Common kubernetes master variables
#-----------------------------------
kube_master_package_version: 1.9.6
kube_master_release_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kube_master_package_version }}/bin/linux/amd64"
kube_master_kubectl_package_url: "{{ kube_master_release_url }}/kubectl"
kube_master_binary_path: /usr/local/bin
kube_master_conf_path: /etc/kubernetes
kube_master_data_dir: /var/lib/kubernetes
kube_master_certs_path: "{{ kube_master_data_dir }}/certs"
kube_master_kubeconfig_path: "{{ kube_master_data_dir }}"
kube_master_tls_cert_file: "{{ kube_master_certs_path }}/kubernetes.pem"
kube_master_tls_key_file: "{{ kube_master_certs_path }}/kubernetes-key.pem"
kube_master_ca_cert_file: "{{ kube_master_certs_path }}/ca.pem"