---

kube_package_version: 1.4.7
kube_release_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kube_package_version }}/bin/linux/amd64"

kube_api_server_package_url: "{{ kube_release_url }}/kube-apiserver"
kube_controller_manager_package_url: "{{ kube_release_url }}/kube-controller-manager"
kube_scheduler_package_url: "{{ kube_release_url }}/kube-scheduler"
kubectl_package_url: "{{ kube_release_url }}/kubectl"