---
#----------------------------------------
# Docker variables for kubernetes workers
#----------------------------------------
version: 1.12.3
release_url: "https://get.docker.com/builds/Linux/x86_64"
binary_path: /usr/local/bin
conf_path: /etc/kubernetes
src_temp_path: /tmp
service_force_restart: no

iptables_enabled: no
ipmasq_enabled: no
host: unix:///var/run/docker.sock
log_level: error
storage_driver: aufs

cert_enable: no
cert_fqdn: docker.k8s.lan