---
#-----------------------------------------
# Kubelet variables for kubernetes workers
#-----------------------------------------
package_url: "{{ kube_worker_release_url }}/kubelet"
binary_path: /usr/bin
certs_path: /var/lib/kubernetes
service_force_restart: no
conf_path: /etc/kubernetes
cloud_provider:
cluster_dns: 10.32.0.10
cluster_domain: cluster.local
configure_cbr0: yes
container_runtime: docker
docker: unix:///var/run/docker.sock
network_plugin: cni
kubeconfig_path: /var/lib/kubelet
reconcile_cidr: yes
serialize_image_pulls: no
verbosity: 2

# Kubeconfig for kubelet
configuration:
  apiVersion: v1
  kind: Config
  users:
  - name: "{{ kubeconfig_name }}"
    user:
      client-certificate: "{{ kube_worker_tls_cert_file }}"
      client-key: "{{ kube_worker_tls_private_key_file }}"
      token: "{{ kubeconfig_user_token }}"
  clusters:
  - name: "{{ kubeconfig_name }}"
    cluster:
      certificate-authority: "{{ kube_worker_tls_ca_file }}"
      server: "{{ kubeconfig_api_server }}"
  contexts:
  - context:
      cluster: "{{ kubeconfig_name }}"
      user: kubelet
    name: kubelet
  current-context: kubelet