---
#-----------------------------------
# Common kubernetes worker variables
#-----------------------------------
kube_worker_package_version: 1.9.6
kube_worker_release_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kube_worker_package_version }}/bin/linux/amd64"
kube_worker_kubectl_package_url: "{{ kube_worker_release_url }}/kubectl"
kube_worker_kubectl_binary_path: /usr/local/bin
kube_worker_allow_privileged: yes
kube_worker_log_level: 2
kube_worker_api_server: https://master0.k8s.lan:6443
kube_worker_certs_path: /var/lib/kubernetes/certs
kube_worker_tls_cert_file: "{{ kube_worker_certs_path }}/kubernetes.pem"
kube_worker_tls_private_key_file: "{{ kube_worker_certs_path }}/kubernetes-key.pem"
kube_worker_tls_ca_file: "{{ kube_worker_certs_path }}/ca.pem"

#---------------------------------------------------
# Kubelet variables for worker cluster configuration
#---------------------------------------------------
kubeconfig_name: kubernetes
kubeconfig_api_server: "{{ kube_worker_api_server }}"
kubeconfig_user_token: hbgith7aWi1aegheifeRhdaiLahVie3z
