---

keepalived_notify: no
keepalived_notify_script_path: /usr/local/sbin
keepalived_notify_script:
keepalived_instances:
  routing_example_1:
    state: master
    priority: 254
    interface: eth0
    router_id: 1
    virtual:
      ip: 10.0.3.253/24
      netmask: 10.0.3.255
      interface: eth0
  routing_example_2:
    state: master
    priority: 254
    interface: eth1
    router_id: 2
    virtual:
      ip: 10.0.3.253/24
      netmask: 10.0.3.255
      interface: eth1