---

- name: configure - define systemd service for etcd
  template:
    src: templates/etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify:
    - restart etcd
  become: yes

- name: enable etcd service
  service:
    name: etcd
    state: started
    enabled: yes
  become: yes
