#----------------------------------
# Set API server defaults variables
#----------------------------------
package_url: "{{ kube_master_release_url }}/kube-apiserver"
bind_address: 0.0.0.0
insecure_bind_address: 127.0.0.1
binary_path: "{{ kube_master_binary_path }}"
conf_path: "{{ kube_master_conf_path }}"
data_dir: "{{ kube_master_data_dir }}"
service_force_restart: no

admission_control:
  - NamespaceLifecycle
  - LimitRanger
  # - SecurityContextDeny
  - ServiceAccount
  - ResourceQuota

tokens:
  - user: admin
    group: admin
    token: prA5ahie3ohtoo4boogvre6quipheaTh
  - user: gpenaud
    group: gpenaud
    token: FWiephivof8onershoong1thee8toso
  - user: kubelet
    group: kubelet
    token: hbgith7aWi1aegheifeRhdaiLahVie3z

allow_privilege: yes
count: 3
authorization_mode: ABAC
authorization_policy_file: /var/lib/kubernetes/authorization-policy.jsonl
enable_swagger_ui: yes
tls_private_key_file: "{{ kube_master_certs_path }}/kubernetes-key.pem"
service_cluster_ip_range: 10.32.0.0/16
service_node_port_range: "30000-32767"
token_auth_file: /var/lib/kubernetes/token.csv
verbosity: 2

etcd_protocol: https
etcd_client_port: 2379
etcd_members:
  - etcd0.lxc.lan
  - etcd1.lxc.lan
  - etcd2.lxc.lan
