---

- name: main - include default variables
  include_vars:
    file: "../../defaults/worker/{{ item }}.yml"
    name: "{{ item | regex_replace('-', '_') }}_default"
  with_items:
    - docker
    - cni
    - kubelet
    - kube-proxy
  tags: always

- name: main - merge default variables with overriden ones
  set_fact:
    "{{ item.variable }}": "{{ item.default | combine(item.data) }}"
  with_items:
    - variable: docker
      data: "{{ docker | default({}) }}"
      default: "{{ docker_default | default({})}}"
    - variable: cni
      data: "{{ cni | default({})}}"
      default: "{{ cni_default | default({})}}"
    - variable: kubelet
      data: "{{ kubelet | default({})}}"
      default: "{{ kubelet_default | default({})}}"
    - variable: kube_proxy
      data: "{{ kube_proxy | default({})}}"
      default: "{{ kube_proxy_default | default({})}}"
  no_log: yes
  tags: always

- name: main - install docker
  include: docker.yml
  tags:
    - docker

- name: main - install cni plugin
  include: cni.yml
  tags:
    - cni

- name: main - install kubelet server
  include: kubelet.yml
  tags:
    - kubelet

- name: main - install kube-proxy server
  include: kube-proxy.yml
  tags:
    - kube-proxy

- name: main - restart services if needed
  meta: flush_handlers
  when: kubelet.service_force_restart or kube_proxy.service_force_restart or docker.service_force_restart

- name: main - download kubectl binary
  get_url:
    url: "{{ kube_worker_kubectl_package_url }}"
    dest: "{{ kube_worker_binary_path }}/kubectl"
    mode: 0755
  become: yes
