---

- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  become: yes

- name: restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
  become: yes

- name: restart kube-proxy
  systemd:
    name: kube-proxy
    daemon_reload: yes
    state: restarted
  become: yes