---

- name: restart kube-apiserver
  systemd:
    name: kube-apiserver
    daemon_reload: yes
    state: restarted
  become: yes

- name: restart kube-controller-manager
  systemd:
    name: kube-controller-manager
    daemon_reload: yes
    state: restarted
  become: yes

- name: restart kube-scheduler
  systemd:
    name: kube-scheduler
    daemon_reload: yes
    state: restarted
  become: yes

- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  become: yes

- name: restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
  become: yes

- name: restart kube-proxy
  systemd:
    name: kube-proxy
    daemon_reload: yes
    state: restarted
  become: yes