Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')

IMAGE = 'debian/stretch64'
NODES = [
  'vagrant-boxes-base-with-dhcp'
]

CONFIGURATION_VERSION = 2
Vagrant.configure(CONFIGURATION_VERSION) do |config|
  config.vm.box = IMAGE

  NODES.each do |node_name|
    config.vm.define node_name do |node|
      node.vm.hostname = node_name
      node.vm.provider :lxc do |lxc|
        lxc.container_name  = :machine
        lxc.customize 'network.link', 'lxc-bridge'
      end

      #
      # Run functionnal test playbook
      #
      config.vm.provision "ansible", run: "always" do |ansible|
        ansible.playbook    = 'test.yml'
        ansible.config_file = '../../ansible.cfg'
        ansible.groups = {
          "vagrant-box" => ["vagrant-boxes-base-with-dhcp"]
        }
      end
    end
  end
end
