---
etcd_package_version: 3.0.15
etcd_archive_name: etcd-v{{ etcd_package_version }}-linux-amd64
etcd_package_url: "https://github.com/coreos/etcd/releases/download/v{{ etcd_package_version }}/{{ etcd_archive_name }}.tar.gz"

etcd_binary_dir: /usr/local/bin
etcd_data_dir: /var/lib/etcd
etcd_src_temp_dir: /tmp/etcd

etcd_debug: yes
etcd_protocol: https
etcd_client_port: 2379
etcd_server_port: 2380

# tls
etcd_tls_certs_path: /etc/etcd
etcd_tls_cert_file: "{{ etcd_tls_certs_path }}/kubernetes.pem"
etcd_tls_peer_cert_file: "{{ etcd_tls_certs_path }}/kubernetes.pem"
etcd_tls_key_file: "{{ etcd_tls_certs_path }}/kubernetes-key.pem"
etcd_tls_peer_key_file: "{{ etcd_tls_certs_path }}/kubernetes-key.pem"
etcd_tls_trusted_ca_file: "{{ etcd_tls_certs_path }}/ca.pem"
etcd_tls_peer_trusted_ca_file: "{{ etcd_tls_certs_path }}/ca.pem"

# listening clients
etcd_clients_listening:
  - "{{ etcd_protocol }}://{{ ansible_default_ipv4.address }}:{{ etcd_client_port }}"
  - "{{ etcd_protocol }}://127.0.0.1:{{ etcd_client_port }}"

etcd_clients_advertising:
  - "{{ etcd_protocol }}://{{ ansible_default_ipv4.address }}:{{ etcd_client_port }}"

# etcd cluster definition
cluster_members: "{{ groups['all'] | sort }}"
etcd_cluster: |
  {% for member in cluster_members -%}
  {{ member }}={{ etcd_protocol }}://{{ hostvars[member].ansible_default_ipv4.address }}:{{ etcd_server_port }},
  {%- endfor %}