---
dependencies: []

galaxy_info:
  author: gpenaud
  description: Docker for Linux.
  company: "My private company"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - jessie
  - name: Ubuntu
    versions:
    - trusty
    - xenial
  galaxy_tags:
    - web
    - system
    - containers
    - docker
    - orchestration
    - compose
    - server
