---
- name: Huge hack to avoid libvirt strange bug
  hosts: vagrant-box
  become: yes

  vars:
    user:                   "{{ lookup('env', 'ANSIBLE_PERSONAL_USER') }}"
    password:               "{{ lookup('env', 'ANSIBLE_PERSONAL_PASSWORD') }}"
    key_file:               "{{ lookup('env', 'ANSIBLE_PERSONAL_PUBKEYFILE') }}"

  tasks:
    - name: template out interfaces file
      copy:
        content: |
          auto lo
          iface lo inet loopback

          {% for interface in (hostvars[ansible_hostname]['ansible_interfaces'] | difference(['lo'])) %}
          auto {{ interface }}
          iface {{ interface }} inet dhcp
          {% endfor %}
        dest: /etc/network/interfaces
        backup: yes

    - name: template out dhclient hook file
      copy:
        content: |
          if [ "$reason" = "BOUND" ] || [ "$reason" = "RENEW" ] || [ "$reason" = "REBIND" ] || [ "$reason" = "REBOOT" ]; then
            echo new_ip_address=$new_ip_address
            echo new_host_name=$new_host_name
            echo new_domain_name=$new_domain_name

            new_fqdn="$new_host_name.$new_domain_name"
            echo new_fqdn=$new_fqdn

            echo "127.0.0.1 $new_fqdn $new_host_name" > /etc/hosts
            echo "$new_ip_address $new_fqdn $new_host_name" >> /etc/hosts
          fi

          exit 0
        dest: /etc/dhcp/dhclient-exit-hooks.d/hostname
        mode: 0700
        backup: yes

    - name: remove dotfiles repository
      file:
        path: "{{ lookup('env', 'HOME') }}/dotfiles"
        state: absent
        force: yes

    - name: checkout dotfiles repository from my personal github account
      git:
        repo: "https://github.com/{{ user }}/dotfiles.git"
        dest: "{{ lookup('env', 'HOME') }}/dotfiles"
        force: yes
      become_user: "{{ user }}"

    - name: execute setup.sh from dotfiles repository
      command: "bash {{ lookup('env', 'HOME') }}/dotfiles/setup.sh"
      environment:
        DOTFILES_DIR: "{{ lookup('env', 'HOME') }}/dotfiles"
        DOTFILES_ENV_FILE: lxc
      become_user: "{{ user }}"